'use strict';

var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({

  REQUEST_REPO: null,
  REQUEST_REPO_SUCCESS: null,
  REQUEST_REPO_ERROR: null,

  REQUEST_PROJECT: null,
  REQUEST_PROJECT_SUCCESS: null,
  REQUEST_PROJECT_ERROR: null,

  REQUEST_REPO_README: null,
  REQUEST_REPO_README_SUCCESS: null,
  REQUEST_REPO_README_ERROR: null,

  REQUEST_ISSUES: null,
  REQUEST_ISSUES_SUCCESS: null,
  REQUEST_ISSUES_ERROR: null,

  REQUEST_DISCUSSIONS: null,
  REQUEST_DISCUSSIONS_SUCCESS: null,
  REQUEST_DISCUSSIONS_ERROR: null

});