#!/bin/bash

set -e

git checkout -b release
PRERELEASE_BUILD='true' webpack -p --color --display-error-details --config webpack.config.js --bail 2>&1
git add .
git commit -am 'release build'
git push origin :gh-pages
git subtree push --prefix public origin gh-pages
git checkout master
git branch -D release