#!/bin/bash

set -e

git checkout -b release
PRERELEASE_BUILD='true' webpack -p --color --display-error-details
git add .
git commit -am 'release build'
git subtree push --prefix public origin gh-pages
git branch -D release